const express=require('express'),path=require('path'),https=require('https'),{analyzeSetups}=require('./src/multi-setup-engine'),tracker=require('./src/trade-tracker');
const app=express(),PORT=process.env.PORT||3000,marketState={symbols:{}},signalState={},outcomeState={},coinbaseState={connected:false,lastSeen:null,error:null};
const SYMBOL='BTCUSD',TFS=['M1','M3','M5','M15','H1','H4','D1'],ENTRY_TF={SCALPING:'M1',INTRADAY:'M5',SWING:'M15'};
app.use(express.json({limit:'2mb'}));app.use(express.static(path.join(__dirname,'public')));
function normalizeSymbol(s=''){s=String(s).toUpperCase();if(s.includes('BTCUSD')||s.includes('BTC-USD')||s==='BTC')return SYMBOL;return s.replace(/[^A-Z0-9]/g,'').slice(0,24)}
function btcOnly(req,res,next){if(normalizeSymbol(req.params?.symbol||req.body?.symbol||SYMBOL)!==SYMBOL)return res.status(400).json({ok:false,error:'BTCUSD_ONLY'});next()}
function bridgeAuth(q,r,n){const e=process.env.MT5_BRIDGE_TOKEN;if(!e||q.get('x-bridge-token')===e)return n();r.status(401).json({ok:false})}
function telegram(text){const token=process.env.TELEGRAM_BOT_TOKEN,chat=process.env.TELEGRAM_CHAT_ID;if(!token||!chat)return Promise.resolve(false);return new Promise(resolve=>{const body=JSON.stringify({chat_id:chat,text}),q=https.request({hostname:'api.telegram.org',path:`/bot${token}/sendMessage`,method:'POST',headers:{'Content-Type':'application/json','Content-Length':Buffer.byteLength(body)}},r=>{let raw='';r.on('data',d=>raw+=d);r.on('end',()=>{const ok=r.statusCode>=200&&r.statusCode<300;if(!ok)console.error('Telegram send failed HTTP',r.statusCode,raw.slice(0,200));resolve(ok)})});q.on('error',e=>{console.error('Telegram send error',e.message);resolve(false)});q.write(body);q.end()})}
function liveSymbol(){const s=marketState.symbols[SYMBOL]||{},tfs={};for(const tf of TFS){const d=s[tf],age=d?.receivedAt?Date.now()-new Date(d.receivedAt):null;tfs[tf]={ready:!!d?.candles?.length,bars:d?.candles?.length||0,lastSeen:d?.receivedAt||null,ageMs:age}}const core=['M1','M3','M5'],connected=core.every(tf=>tfs[tf].ready&&tfs[tf].ageMs!==null&&tfs[tf].ageMs<90000),d=s.M1||s.M3||s.M5;return{source:'COINBASE',connected,timeframes:tfs,lastSeen:d?.receivedAt||null,price:d?.bid||d?.close||null}}
function trackOutcomes(s){for(const [setup,tf] of Object.entries(ENTRY_TF)){const candles=s?.[tf]?.candles;if(!candles?.length)continue;const before=new Map(tracker.history(SYMBOL,200,setup).map(t=>[t.id,t.result])),list=tracker.update(SYMBOL,candles,setup);for(const t of list)if(t.status==='CLOSED'&&!before.get(t.id)&&outcomeState[t.id]!==t.result){outcomeState[t.id]=t.result;const p=tracker.performance(SYMBOL,'all',setup);telegram(`TRADE RESULT ${setup} ${SYMBOL}\n#${t.id} ${t.side} ${t.result}\nPnL: ${t.pnlPips} pips\nWin Rate ${setup}: ${p.winRate}%`)}}}
function runSetups(trigger='FEED'){const s=marketState.symbols[SYMBOL];if(!s)return null;trackOutcomes(s);const pip=+(process.env.PIP_SIZE_BTCUSD||1),setups=analyzeSetups({symbol:SYMBOL,data:s,pipSize:pip});s.setups=setups;s.smc=setups.SCALPING;s.smcEvaluatedAt=new Date().toISOString();s.smcTrigger=trigger;for(const [name,result] of Object.entries(setups)){const sig=result.signal;if(!sig)continue;const key=[name,sig.side,sig.entry,sig.sl,sig.tp2,sig.setupTime].join(':');if(signalState[name]===key)continue;signalState[name]=key;const t=tracker.addSignal(SYMBOL,sig,{setup:name,bias:result.bias,mssTf:result.entryTf,sweepType:result.liquiditySweep?.type});telegram(`BTC AI SMC ${name}\n${sig.side} LIMIT${t?` #${t.id}`:''}\nEntry: ${sig.entry}\nSL: ${sig.sl} (${sig.slPips} pips)\nTP1: ${sig.tp1} (${sig.tp1Pips} pips / 1R)\nTP2: ${sig.tp2} (${sig.tp2Pips} pips / 2R)\nZone: ${sig.zone}\nQuality: ${sig.quality||'--'}\nTF: ${result.biasTf} -> ${result.confirmTf} -> ${result.entryTf}\nSumber: Coinbase\nAuto Trade: OFF`)}return setups}
function aggregate(src,mins){const sec=mins*60,map=new Map;for(const c of src){const t=Math.floor(c.time/sec)*sec;let x=map.get(t);if(!x){x={time:t,open:c.open,high:c.high,low:c.low,close:c.close,tickVolume:c.tickVolume||0};map.set(t,x)}else{x.high=Math.max(x.high,c.high);x.low=Math.min(x.low,c.low);x.close=c.close;x.tickVolume+=(c.tickVolume||0)}}return[...map.values()].sort((a,b)=>a.time-b.time).slice(-300)}
function coinbaseRequest(granularity=60){return new Promise((resolve,reject)=>{https.get({hostname:'api.exchange.coinbase.com',path:`/products/BTC-USD/candles?granularity=${granularity}`,headers:{'User-Agent':'AI-Trading-SMC-BTC/5.0','Accept':'application/json'}},r=>{let raw='';r.on('data',d=>raw+=d);r.on('end',()=>{if(r.statusCode<200||r.statusCode>=300)return reject(new Error(`HTTP ${r.statusCode}`));try{resolve(JSON.parse(raw))}catch(e){reject(e)}})}).on('error',reject)})}
function rowsToCandles(rows){return rows.map(x=>({time:+x[0],low:+x[1],high:+x[2],open:+x[3],close:+x[4],tickVolume:+x[5]})).filter(c=>[c.time,c.open,c.high,c.low,c.close].every(Number.isFinite)).sort((a,b)=>a.time-b.time).slice(-300)}
async function refreshCoinbase(){try{const [r1,r15,r60,rD]=await Promise.all([coinbaseRequest(60),coinbaseRequest(900),coinbaseRequest(3600),coinbaseRequest(86400)]),m1=rowsToCandles(r1),m15=rowsToCandles(r15),h1=rowsToCandles(r60),d1=rowsToCandles(rD);if(m1.length<20||m15.length<20||h1.length<20||d1.length<20)throw new Error('insufficient HTF candle data');const sets={M1:m1,M3:aggregate(m1,3),M5:aggregate(m1,5),M15:m15,H1:h1,H4:aggregate(h1,240),D1:d1},now=new Date().toISOString(),last=m1.at(-1);marketState.symbols[SYMBOL]??={};for(const [tf,candles] of Object.entries(sets))marketState.symbols[SYMBOL][tf]={...candles.at(-1),candles,receivedAt:now,historyBars:candles.length,bid:last.close,ask:last.close,source:'COINBASE'};coinbaseState.connected=true;coinbaseState.lastSeen=now;coinbaseState.error=null;runSetups('COINBASE')}catch(e){coinbaseState.connected=false;coinbaseState.error=e.message;console.error('Coinbase BTCUSD feed error:',e.message)}}
function statusPayload(){const b=liveSymbol();return{status:b.connected&&coinbaseState.connected?'online':'degraded',engine:'BTC AI SMC V5',market:SYMBOL,database:tracker.performance(SYMBOL).database,databaseReady:tracker.performance(SYMBOL).ready,telegram:{configured:!!(process.env.TELEGRAM_BOT_TOKEN&&process.env.TELEGRAM_CHAT_ID)},feeds:{BTCUSD:{...b,connected:b.connected&&coinbaseState.connected,error:coinbaseState.error}},execution:{enabled:false,mode:'LIMIT_SIGNAL_ONLY'},setups:{SCALPING:'M5-M3-M1',INTRADAY:'H1-M15-M5',SWING:'D1/H4-H1-M15'},rules:{sl:'STRUCTURE_MAX_50_PIPS',tp1:'1R',tp2:'2R',breakEven:false},btcOnly:true}}
app.get('/health',(q,r)=>r.json(statusPayload()));app.get('/api/status',(q,r)=>r.json(statusPayload()));
app.get('/api/telegram/test',async(q,r)=>{const ok=await telegram('BTC AI Trading SMC TEST\nBTCUSD only • Coinbase feed\nScalping + Intraday + Swing\nAuto Trade: OFF');r.status(ok?200:503).json({ok})});
app.post('/api/mt5/history',bridgeAuth,(q,r)=>r.status(410).json({ok:false,error:'MT5_DISABLED_BTCUSD_COINBASE_ONLY'}));app.post('/api/mt5/ohlc',bridgeAuth,(q,r)=>r.status(410).json({ok:false,error:'MT5_DISABLED_BTCUSD_COINBASE_ONLY'}));
app.get('/api/setups/:symbol',btcOnly,(q,r)=>{const x=runSetups('API');x?r.json({ok:true,symbol:SYMBOL,setups:x}):r.status(503).json({ok:false,stage:'COLLECTING_HISTORY'})});
app.get('/api/smc/:symbol',btcOnly,(q,r)=>{const x=runSetups('API');x?.SCALPING?r.json({ok:true,...x.SCALPING}):r.status(503).json({ok:false,stage:'COLLECTING_HISTORY'})});
app.get('/api/performance/:symbol',btcOnly,(q,r)=>r.json({ok:true,...tracker.performance(SYMBOL,q.query.period||'all',q.query.setup?String(q.query.setup).toUpperCase():null)}));
app.get('/api/performance-summary',(q,r)=>r.json({ok:true,symbol:SYMBOL,setups:Object.fromEntries(Object.keys(ENTRY_TF).map(s=>[s,tracker.performance(SYMBOL,'all',s)]))}));
app.get('/api/quality/:symbol',btcOnly,(q,r)=>r.json({ok:true,...tracker.quality(SYMBOL,q.query.period||'all',q.query.setup?String(q.query.setup).toUpperCase():null)}));
app.get('/api/history/:symbol',btcOnly,(q,r)=>r.json({ok:true,trades:tracker.history(SYMBOL,q.query.limit,q.query.setup?String(q.query.setup).toUpperCase():null)}));
app.get('/api/mt5/status',(q,r)=>r.json({connected:false,disabled:true,reason:'BTCUSD_COINBASE_ONLY',coinbase:coinbaseState,engine:'BTC AI SMC V5'}));
app.get('/api/orders/pending',bridgeAuth,(q,r)=>r.json({executionEnabled:false,mode:'LIMIT_SIGNAL_ONLY',orders:[]}));app.use((q,r)=>r.sendFile(path.join(__dirname,'public','index.html')));
tracker.init().then(()=>{app.listen(PORT,'0.0.0.0',()=>console.log(`BTC AI SMC V5 running ${PORT} - BTCUSD ONLY`));refreshCoinbase();setInterval(refreshCoinbase,30000)}).catch(e=>{console.error(e);process.exit(1)});