function swings(bars,w=2){const highs=[],lows=[];for(let i=w;i<bars.length-w;i++){let hi=true,lo=true;for(let j=i-w;j<=i+w;j++){if(j===i)continue;if(bars[j].high>=bars[i].high)hi=false;if(bars[j].low<=bars[i].low)lo=false}if(hi)highs.push({i,price:bars[i].high,time:bars[i].time});if(lo)lows.push({i,price:bars[i].low,time:bars[i].time})}return{highs,lows}}
function bias(bars){if(!bars||bars.length<20)return'NEUTRAL';const s=swings(bars),h=s.highs.slice(-2),l=s.lows.slice(-2);if(h.length<2||l.length<2)return'NEUTRAL';if(h[1].price>h[0].price&&l[1].price>l[0].price)return'BULLISH';if(h[1].price<h[0].price&&l[1].price<l[0].price)return'BEARISH';return'NEUTRAL'}
function confirmedSweep(bars,dir){if(!bars||bars.length<20||dir==='NEUTRAL')return null;const last=Math.min(bars.length-1,Math.max(0,bars.length-1)),from=Math.max(5,bars.length-8);for(let i=last;i>=from;i--){const prior=bars.slice(0,i),s=swings(prior),level=dir==='BULLISH'?s.lows.at(-1):s.highs.at(-1),c=bars[i];if(!level)continue;if(dir==='BULLISH'&&c.low<level.price&&c.close>level.price)return{type:'SELL_SIDE',level:level.price,time:c.time,index:i};if(dir==='BEARISH'&&c.high>level.price&&c.close<level.price)return{type:'BUY_SIDE',level:level.price,time:c.time,index:i}}return null}
function avgBody(bars,end,n=10){const a=bars.slice(Math.max(0,end-n),end);return a.length?a.reduce((s,c)=>s+Math.abs(c.close-c.open),0)/a.length:0}
function displacement(bars,dir,afterTime){if(!bars?.length)return null;for(let i=0;i<bars.length;i++){const c=bars[i];if(c.time<=afterTime)continue;const body=Math.abs(c.close-c.open),avg=avgBody(bars,i,10),range=c.high-c.low;if(!avg||!range)continue;const directional=dir==='BULLISH'?c.close>c.open:c.close<c.open;if(directional&&body>=avg*1.5&&body/range>=0.6)return{direction:dir,time:c.time,index:i,body,avgBody:avg,high:c.high,low:c.low}}return null}
function mssAfter(bars,dir,afterTime){if(!bars||bars.length<10)return null;for(let i=5;i<bars.length;i++){const c=bars[i];if(c.time<=afterTime)continue;const s=swings(bars.slice(0,i));if(dir==='BULLISH'){const h=s.highs.at(-1);if(h&&c.close>h.price)return{direction:dir,level:h.price,time:c.time,index:i}}else{const l=s.lows.at(-1);if(l&&c.close<l.price)return{direction:dir,level:l.price,time:c.time,index:i}}}return null}
function zoneAfter(bars,dir,disp,mss){if(!disp||!mss)return null;const start=Math.max(0,disp.index-3),end=Math.min(bars.length-1,mss.index);let ob=null,fvg=null;for(let i=start;i<=end;i++){const b=bars[i];if(dir==='BULLISH'&&b.close<b.open)ob={low:b.low,high:b.high,time:b.time,index:i,type:'OB'};if(dir==='BEARISH'&&b.close>b.open)ob={low:b.low,high:b.high,time:b.time,index:i,type:'OB'};if(i>=2){const a=bars[i-2],c=bars[i];if(dir==='BULLISH'&&c.low>a.high)fvg={low:a.high,high:c.low,time:c.time,index:i,type:'FVG'};if(dir==='BEARISH'&&c.high<a.low)fvg={low:c.high,high:a.low,time:c.time,index:i,type:'FVG'}}}return fvg||ob}
function retestAfter(bars,zone,dir,afterTime){if(!zone)return null;for(let i=0;i<bars.length;i++){const c=bars[i];if(c.time<=afterTime)continue;const touches=c.low<=zone.high&&c.high>=zone.low;if(!touches)continue;const midpoint=(zone.low+zone.high)/2,confirmed=dir==='BULLISH'?c.close>=midpoint:c.close<=midpoint;if(confirmed)return{time:c.time,index:i,price:midpoint,candle:c}}return null}
function analyze({symbol,m15,m5,m3,pipSize=0.1}){const b=bias(m15);let stage=b==='NEUTRAL'?'WAITING_M15_BIAS':'WAITING_LIQUIDITY_SWEEP',sw=null,disp=null,ms5=null,ms3=null,zone=null,retest=null,signal=null;if(b!=='NEUTRAL'){sw=confirmedSweep(m5,b);if(sw){stage='WAITING_DISPLACEMENT';disp=displacement(m3,b,sw.time)||displacement(m5,b,sw.time);if(disp){stage='WAITING_MSS';ms5=mssAfter(m5,b,disp.time);ms3=mssAfter(m3,b,disp.time);const ms=ms3||ms5;if(ms){stage='WAITING_RETEST';zone=zoneAfter(m3,b,disp,ms3||{...ms,index:m3.findIndex(c=>c.time>=ms.time)});if(zone){retest=retestAfter(m3,zone,b,ms.time);if(retest){const entry=(zone.low+zone.high)/2,side=b==='BULLISH'?'BUY':'SELL',sign=side==='BUY'?1:-1;signal={side,type:'LIMIT',entry:Number(entry.toFixed(3)),sl:Number((entry-sign*50*pipSize).toFixed(3)),tp1:Number((entry+sign*50*pipSize).toFixed(3)),tp2:Number((entry+sign*100*pipSize).toFixed(3)),breakEvenAfterPips:30,slPips:50,tp1Pips:50,tp2Pips:100,zone:zone.type,setupTime:retest.time};stage=`${side}_LIMIT_READY`}}}}}}return{symbol,bias:b,stage,liquiditySweep:sw,displacement:disp,mssM5:ms5,mssM3:ms3,orderBlock:zone?.type==='OB'?zone:null,fvg:zone?.type==='FVG'?zone:null,retest,signal,executionEnabled:false,updatedAt:new Date().toISOString()}}
module.exports={analyze};
