function swings(bars,w=2){const highs=[],lows=[];for(let i=w;i<bars.length-w;i++){let hi=true,lo=true;for(let j=i-w;j<=i+w;j++){if(j===i)continue;if(bars[j].high>=bars[i].high)hi=false;if(bars[j].low<=bars[i].low)lo=false}if(hi)highs.push({i,price:bars[i].high,time:bars[i].time});if(lo)lows.push({i,price:bars[i].low,time:bars[i].time})}return{highs,lows}}
function bias(bars){if(!bars||bars.length<20)return'NEUTRAL';const s=swings(bars),h=s.highs.slice(-2),l=s.lows.slice(-2);if(h.length<2||l.length<2)return'NEUTRAL';if(h[1].price>h[0].price&&l[1].price>l[0].price)return'BULLISH';if(h[1].price<h[0].price&&l[1].price<l[0].price)return'BEARISH';return'NEUTRAL'}
function confirmedSweep(bars,dir){if(!bars||bars.length<20||dir==='NEUTRAL')return null;const from=Math.max(5,bars.length-10);for(let i=bars.length-1;i>=from;i--){const s=swings(bars.slice(0,i)),level=dir==='BULLISH'?s.lows.at(-1):s.highs.at(-1),c=bars[i];if(!level)continue;if(dir==='BULLISH'&&c.low<level.price&&c.close>level.price)return{type:'SELL_SIDE',level:level.price,time:c.time,index:i};if(dir==='BEARISH'&&c.high>level.price&&c.close<level.price)return{type:'BUY_SIDE',level:level.price,time:c.time,index:i}}return null}
function avgBody(bars,end,n=10){const a=bars.slice(Math.max(0,end-n),end);return a.length?a.reduce((s,c)=>s+Math.abs(c.close-c.open),0)/a.length:0}
function displacement(bars,dir,afterTime){if(!bars?.length)return null;for(let i=0;i<bars.length;i++){const c=bars[i];if(c.time<=afterTime)continue;const body=Math.abs(c.close-c.open),avg=avgBody(bars,i,10),range=c.high-c.low,directional=dir==='BULLISH'?c.close>c.open:c.close<c.open;if(avg&&range&&directional&&body>=avg*1.4&&body/range>=.58)return{direction:dir,time:c.time,index:i,body,avgBody:avg,high:c.high,low:c.low}}return null}
function mssAfter(bars,dir,afterTime){if(!bars||bars.length<10)return null;for(let i=5;i<bars.length;i++){const c=bars[i];if(c.time<=afterTime)continue;const s=swings(bars.slice(0,i));if(dir==='BULLISH'){const h=s.highs.at(-1);if(h&&c.close>h.price)return{direction:dir,level:h.price,time:c.time,index:i}}else{const l=s.lows.at(-1);if(l&&c.close<l.price)return{direction:dir,level:l.price,time:c.time,index:i}}}return null}
function goldenRange(bars,dir,disp,mss){if(!disp||!mss)return null;const from=Math.max(0,disp.index),to=Math.min(bars.length-1,mss.index),leg=bars.slice(from,to+1);if(!leg.length)return null;const low=Math.min(...leg.map(c=>c.low)),high=Math.max(...leg.map(c=>c.high)),range=high-low;if(!(range>0))return null;const a=dir==='BULLISH'?high-range*.786:low+range*.618,b=dir==='BULLISH'?high-range*.618:low+range*.786;return{low:Math.min(a,b),high:Math.max(a,b),fib618:dir==='BULLISH'?high-range*.618:low+range*.618,fib786:dir==='BULLISH'?high-range*.786:low+range*.786,swingLow:low,swingHigh:high}}
function overlap(a,b){return!!(a&&b&&a.low<=b.high&&a.high>=b.low)}
function zonesAfter(bars,dir,disp,mss){if(!disp||!mss)return{ob:null,fvg:null,golden:null,zone:null,quality:null};const start=Math.max(0,disp.index-3),end=Math.min(bars.length-1,mss.index),golden=goldenRange(bars,dir,disp,mss);let ob=null,fvg=null;for(let i=start;i<=end;i++){const b=bars[i];if(dir==='BULLISH'&&b.close<b.open)ob={low:b.low,high:b.high,time:b.time,index:i,type:'OB'};if(dir==='BEARISH'&&b.close>b.open)ob={low:b.low,high:b.high,time:b.time,index:i,type:'OB'};if(i>=2){const a=bars[i-2],c=bars[i];if(dir==='BULLISH'&&c.low>a.high)fvg={low:a.high,high:c.low,time:c.time,index:i,type:'FVG'};if(dir==='BEARISH'&&c.high<a.low)fvg={low:c.high,high:a.low,time:c.time,index:i,type:'FVG'}}}const obGolden=overlap(ob,golden),fvgGolden=overlap(fvg,golden);let zone=null,quality=null;if(ob&&obGolden&&fvg&&fvgGolden&&overlap(ob,fvg)){const low=Math.max(ob.low,fvg.low,golden.low),high=Math.min(ob.high,fvg.high,golden.high);if(low<=high){zone={low,high,time:Math.max(ob.time,fvg.time),index:Math.max(ob.index,fvg.index),type:'OB+FVG+GOLDEN'};quality='A+'}}if(!zone&&ob&&obGolden){const low=Math.max(ob.low,golden.low),high=Math.min(ob.high,golden.high);if(low<=high){zone={low,high,time:ob.time,index:ob.index,type:'OB+GOLDEN'};quality='A'}}if(!zone&&fvg&&fvgGolden){const low=Math.max(fvg.low,golden.low),high=Math.min(fvg.high,golden.high);if(low<=high){zone={low,high,time:fvg.time,index:fvg.index,type:'FVG+GOLDEN'};quality='B'}}return{ob,fvg,golden,zone,quality}}
function retestAfter(bars,zone,dir,afterTime){if(!zone)return null;for(let i=0;i<bars.length;i++){const c=bars[i];if(c.time<=afterTime)continue;if(c.low>zone.high||c.high<zone.low)continue;const midpoint=(zone.low+zone.high)/2,confirmed=dir==='BULLISH'?c.close>=midpoint:c.close<=midpoint;if(confirmed)return{time:c.time,index:i,price:midpoint,candle:c}}return null}
function structureRisk(bars,side,entry,retestIndex,pipSize){const s=swings(bars),candidates=side==='BUY'?s.lows.filter(x=>x.i<=retestIndex&&x.price<entry):s.highs.filter(x=>x.i<=retestIndex&&x.price>entry),last=candidates.at(-1);if(!last)return{riskPips:50,structure:null,fallback:true};const raw=side==='BUY'?(entry-last.price)/pipSize:(last.price-entry)/pipSize,risk=Math.max(1,Math.min(50,raw));return{riskPips:risk,structure:last,fallback:false}}
function analyze({symbol,m5,m3,m1,pipSize=.1}){const b=bias(m5);let stage=b==='NEUTRAL'?'WAITING_M5_BIAS':'WAITING_M3_CONFIRMATION',sw=null,ms3=null,disp=null,ms1=null,zones=null,zone=null,retest=null,signal=null;if(b!=='NEUTRAL'){ms3=mssAfter(m3,b,0);if(ms3){stage='WAITING_M1_SWEEP';sw=confirmedSweep(m1,b);if(sw){stage='WAITING_M1_DISPLACEMENT';disp=displacement(m1,b,sw.time);if(disp){stage='WAITING_M1_MSS';ms1=mssAfter(m1,b,disp.time);if(ms1){stage='WAITING_GOLDEN_ZONE';zones=zonesAfter(m1,b,disp,ms1);zone=zones.zone;if(zone){stage='WAITING_M1_RETEST';retest=retestAfter(m1,zone,b,ms1.time);if(retest){const entry=(zone.low+zone.high)/2,side=b==='BULLISH'?'BUY':'SELL',sign=side==='BUY'?1:-1,r=structureRisk(m1,side,entry,retest.index,pipSize),risk=Number(r.riskPips.toFixed(1));signal={side,type:'LIMIT',entry:Number(entry.toFixed(3)),sl:Number((entry-sign*risk*pipSize).toFixed(3)),tp1:Number((entry+sign*risk*pipSize).toFixed(3)),tp2:Number((entry+sign*risk*2*pipSize).toFixed(3)),slPips:risk,tp1Pips:risk,tp2Pips:Number((risk*2).toFixed(1)),riskReward:'1:2',slMode:r.fallback?'MAX_50_NO_VALID_STRUCTURE':'ENTRY_TF_STRUCTURE_MAX_50',slStructure:r.structure,zone:zone.type,quality:zones.quality,goldenFib:true,setupTime:retest.time};stage=`${side}_LIMIT_READY`}}}}}}}return{symbol,bias:b,biasTf:'M5',confirmTf:'M3',entryTf:'M1',stage,liquiditySweep:sw,displacement:disp,mssM3:ms3,mssM1:ms1,orderBlock:zones?.ob||null,fvg:zones?.fvg||null,goldenFib:zones?.golden||null,selectedZone:zone,setupQuality:zones?.quality||null,retest,signal,executionEnabled:false,engine:'SMC V4 SCALPING GOLDEN STRUCTURE RR1:2',updatedAt:new Date().toISOString()}}
module.exports={analyze};
