const trades=[];let seq=1;
function pipSize(symbol){return symbol==='XAUUSD'?Number(process.env.PIP_SIZE_XAUUSD||0.1):Number(process.env.PIP_SIZE_BTCUSD||1)}
function addSignal(symbol,sig,meta={}){const key=[symbol,sig.side,sig.entry,sig.sl,sig.tp2].join(':');if(trades.some(t=>t.key===key&&['PENDING','OPEN'].includes(t.status)))return null;const t={id:seq++,key,symbol,side:sig.side,entry:sig.entry,sl:sig.sl,tp1:sig.tp1,tp2:sig.tp2,beTriggerPips:30,zone:sig.zone,bias:meta.bias||null,status:'PENDING',tp1Hit:false,beArmed:false,result:null,pnlPips:0,createdAt:new Date().toISOString(),openedAt:null,closedAt:null,exitPrice:null};trades.unshift(t);if(trades.length>500)trades.pop();return t}
function crossed(c,price){return c.low<=price&&c.high>=price}
function update(symbol,candles){const p=pipSize(symbol);for(const t of trades.filter(x=>x.symbol===symbol&&!['CLOSED','CANCELLED'].includes(x.status))){for(const c of candles.slice(-100)){if(t.status==='PENDING'){if(!crossed(c,t.entry))continue;t.status='OPEN';t.openedAt=new Date(Number(c.time)*1000).toISOString()}
if(t.status!=='OPEN')continue;const buy=t.side==='BUY';const bePrice=t.entry+(buy?1:-1)*t.beTriggerPips*p;const hitSL=buy?c.low<=t.sl:c.high>=t.sl;const hitTP1=buy?c.high>=t.tp1:c.low<=t.tp1;const hitTP2=buy?c.high>=t.tp2:c.low<=t.tp2;const hitBETrigger=buy?c.high>=bePrice:c.low<=bePrice;
// Conservative same-candle ordering: adverse SL wins if SL and target are both touched in the same OHLC candle.
if(hitSL){close(t,t.sl,-50,'SL',c);break}if(hitBETrigger)t.beArmed=true;if(hitTP1)t.tp1Hit=true;if(hitTP2){close(t,t.tp2,100,'TP2',c);break}if(t.beArmed){const returned=buy?c.low<=t.entry:c.high>=t.entry;if(returned){close(t,t.entry,0,'BE',c);break}}}}
return trades.filter(x=>x.symbol===symbol)}
function close(t,price,pips,result,c){t.status='CLOSED';t.exitPrice=price;t.pnlPips=pips;t.result=result;t.closedAt=new Date(Number(c.time)*1000).toISOString()}
function performance(symbol){const all=trades.filter(t=>!symbol||t.symbol===symbol),closed=all.filter(t=>t.status==='CLOSED'),wins=closed.filter(t=>t.pnlPips>0),losses=closed.filter(t=>t.pnlPips<0),be=closed.filter(t=>t.pnlPips===0),grossWin=wins.reduce((a,t)=>a+t.pnlPips,0),grossLoss=Math.abs(losses.reduce((a,t)=>a+t.pnlPips,0));return{symbol:symbol||'ALL',totalTrades:all.length,closedTrades:closed.length,openTrades:all.filter(t=>t.status==='OPEN').length,pendingTrades:all.filter(t=>t.status==='PENDING').length,wins:wins.length,losses:losses.length,breakEven:be.length,winRate:closed.length?Number((wins.length/closed.length*100).toFixed(2)):0,netPips:closed.reduce((a,t)=>a+t.pnlPips,0),profitFactor:grossLoss?Number((grossWin/grossLoss).toFixed(2)):grossWin?null:0}}
function history(symbol,limit=50){return trades.filter(t=>!symbol||t.symbol===symbol).slice(0,Math.min(Number(limit)||50,200))}
module.exports={addSignal,update,performance,history};